DECLARE @I AS INT=0
DECLARE @ADDRESSID AS INT 
DECLARE @USERID AS INT
DECLARE @DATE_ AS DATETIME

WHILE @I<7500
BEGIN
	SET @I = @I + 1
	-- Selecting a random user ID
	SELECT TOP 1  @USERID=ID FROM DEMIREL.DBO.USERS ORDER BY NEWID()
	-- Selecting a random address ID for the selected user
	SELECT TOP 1 @ADDRESSID=ID FROM DEMIREL.DBO.ADDRESS_ WHERE USERID=@USERID  ORDER BY NEWID()
	-- Generating a random date
	SET @DATE_=DATEADD(DAY,RAND()*450,'20170101')
	SET @DATE_=DATEADD(HOUR,RAND()*24,@DATE_) 
	SET @DATE_=DATEADD(MINUTE,RAND()*60,@DATE_) 
	SET @DATE_=DATEADD(SECOND,RAND()*60,@DATE_) 

	-- Inserting data into the ORDERS_ table
	INSERT INTO DEMIREL.DBO.ORDERS_(USERID,DATE_,TOTALPRICE,STATUS_,ADDRESSID)
		VALUES (@USERID,@DATE_,0,0,@ADDRESSID)
END
