--INSERT INTO USERNAME_ COLUMN
use DEMIREL
 INSERT INTO USERS (USERNAME_)
SELECT CONCAT(LOWER(NAME_), LOWER(SURNAME), '_')
FROM USERS;

--INSERT INTO EMAIL COLUMN
use DEMIREL
 INSERT INTO USERS (EMAIL)
SELECT CONCAT(LOWER(NAME_), LOWER(SURNAME), '@demirel.com')
FROM USERS;



