DECLARE @I AS INT = 0
DECLARE @INVOICEID AS INT
DECLARE @ORDERID AS INT
DECLARE @ITEMID AS INT
DECLARE @ITEMNAME AS VARCHAR(50)
DECLARE @AMOUNT AS INT
DECLARE @UNITPRICE AS FLOAT
DECLARE @LINETOTAL AS FLOAT

WHILE @I < 10000
BEGIN
    SET @I = @I + 1  -- Increment the loop counter

    -- Select a random invoice ID from the DEMIREL.DBO.INVOICES table
    SELECT TOP 1 @INVOICEID = ID FROM DEMIREL.DBO.INVOICES ORDER BY NEWID()

    -- Select a random order ID associated with the selected invoice ID
    SELECT TOP 1 @ORDERID = ORDERID FROM INVOICES WHERE @INVOICEID = ID ORDER BY NEWID()
    
    -- Add a check to skip if the order ID already exists in INVOICEDETAILS
    IF EXISTS (SELECT 1 FROM INVOICEDETAILS WHERE ORDERID = @ORDERID)
        CONTINUE
    
	-- Select a random item ID associated with the selected order ID
    SELECT TOP 1 @ITEMID = ITEMID FROM ORDERDETAILS_ WHERE @ORDERID = ID ORDER BY NEWID()

    -- Select the item name, amount, unit price, and line total for the selected order ID
    SELECT TOP 1 @ITEMNAME = ITEMNAME FROM ITEMS WHERE ID = @ITEMID ORDER BY NEWID()
    SELECT TOP 1 @AMOUNT = AMOUNT FROM ORDERDETAILS_ WHERE @ORDERID = ID ORDER BY NEWID()
    SELECT TOP 1 @UNITPRICE = UNITPRICE FROM ORDERDETAILS_ WHERE @ORDERID = ID ORDER BY NEWID()
    SELECT TOP 1 @LINETOTAL = LINETOTAL FROM ORDERDETAILS_ WHERE @ORDERID = ID ORDER BY NEWID()

    -- Insert the invoice details into the INVOICEDETAILS222 table
    INSERT INTO INVOICEDETAILS (INVOICEID, ORDERID, ITEMID, ITEMNAME, AMOUNT, UNITPRICE, LINETOTAL)
		VALUES (@INVOICEID, @ORDERID, @ITEMID, @ITEMNAME, @AMOUNT, @UNITPRICE, @LINETOTAL)
END

SELECT * FROM INVOICEDETAILS

